### ISSUE TITLE
Link (and maybe new list) suggestion

### ISSUE THREAD

**Issue by billturner** [markerikson/react-redux-links#1]
Howdy! I didn't already see a page/list dedicated to async kinds of things, so this may be a good starter. Dan Abramov answered a question about using `setTimeout` in an action, but instead suggests best use case for Thunk: http://stackoverflow.com/questions/35411423/how-to-dispatch-a-redux-action-with-a-timeout/35415559#35415559

Lots of code samples and explanations.

**Comment by markerikson** [comment]
Certainly interested in adding some more categories to the list.  There's also overlap with what should actually go into the Redux docs themselves.  I've got an issue open for adding an FAQ to the Redux docs ( https://github.com/reactjs/redux/issues/1312 ), and am hoping to help contribute to putting that together.

**Comment by billturner** [comment]
That makes sense, and that sort of answer does belong more on a FAQ page. Looking forward to seeing where that goes. Thanks!
