### ISSUE TITLE
Remove experimental proposal warning from React Hooks section

### ISSUE THREAD

**Issue by bpas247** [markerikson/react-redux-links#118]
> Note: Hooks are still an experimental proposal, available in an alpha release. The API will likely change. Keep that in mind as you try them out.

https://github.com/markerikson/react-redux-links/blob/master/react-hooks.md#react-hooks
I have a feeling this is a little dated, should we go ahead and remove it?

**Comment by markerikson** [comment]
Haha, yes, indeed!  Go ahead and submit a PR.
