### ISSUE TITLE
(docs): Relative Links are broken at Repository Main Page

### ISSUE THREAD

**Issue by armand1m** [markerikson/react-redux-links#25]
# Issue

When you try to navigate clicking in the links at the README.md rendered on the repo main page, it actually is using the last resource of the url (the repo name) and replacing with the .md filename.

When you open the README.md content and click on them they work just fine, since you're browsing through the blob files of the repo.

# Proposed Solution

Was reading this article https://help.github.com/articles/relative-links-in-readmes/, and absolute paths are not recommended. So I would recommend you to put a relative link operand (`./path/to/file.md`) in each link so it can be found.

**Comment by markerikson** [comment]
This seems to be some sort of a Github bug.  See https://twitter.com/dan_abramov/status/775332942268755969 and http://stackoverflow.com/questions/39445387/relative-link-in-readme-broken-if-readme-viewed-automatically-by-repo .  Not much I can do about it at the moment.

**Comment by markerikson** [comment]
Yep, see https://github.com/github/markup/issues/926 for details.

**Comment by armand1m** [comment]
At the same time I'm laughing and I'm crying inside about it, sorry for the inconvenience! =)

**Comment by markerikson** [comment]
Heh, no problem.  I actually only knew something was wrong because someone pinged me on Twitter overnight, and Dan Abramov replied to us.  Plus, you don't normally expect it to be a GH bug.
