### ISSUE TITLE
Looking for info on testing redux w/Jest +0.14

### ISSUE THREAD

**Issue by michaelryancaputo** [markerikson/react-redux-links#26]
Know of any articles? I can't find any (yet)

**Comment by markerikson** [comment]
Not specifically, no.  I'm using Mocha+Chai+Sinon+Enzyme myself, so a number of the articles I've collected have been about that stack.  Per my comment on Twitter, this list generally reflects stuff I use or at least understand, and so it's missing stuff I don't use like routing or React Native.  If you do find some good articles or info, PRs are welcome!
