### ISSUE TITLE
Make this an awesome list

### ISSUE THREAD

**Issue by afang** [markerikson/react-redux-links#4]
Any plans on turning this into an [Awesome](https://github.com/sindresorhus/awesome) list? This already follows a similar format so it wouldn't be a big hassle to submit it.

**Comment by markerikson** [comment]
Not really.  Most of those seem to be "just" links, with minimal description and not a lot of filtering.  I see this list as a more curated list of higher-quality links - ie, not _every_ boilerplate, but 7-8 good boilerplates that cover several different approaches; not _every_ React tutorial, but the ones that are better written and more informative, etc.
