### ISSUE TITLE
First React Server Rendering link is broken

### ISSUE THREAD

**Issue by mherodev** [markerikson/react-redux-links#44]
This link:

https://codingbox.io/react-for-beginners-creating-isomorphic-react-redux-app-and-deploying-it-on-heroku-6a313f8f3693

It navigates to medium, weirdly.

**Comment by markerikson** [comment]
Looks like Codingbox.io is/was a custom domain pointing to a Medium publication.  That does seem to be busted now.  Just updated the llink to point to the current Medium.com URL.  Thanks!
