### ISSUE TITLE
Add the "Redux Book"

### ISSUE THREAD

**Issue by borisd** [markerikson/react-redux-links#54]
Hi, 

Not sure where its best to add in on the page a reference to "The Complete Redux Book" (http://redux-book.com/)

**Comment by markerikson** [comment]
Hiya.  It's actually already listed here: https://github.com/markerikson/react-redux-links/blob/master/redux-tutorials.md#paid-courses-and-books .

:)

I do need to update the listing, since it's clearly been finished since I added it last May.

**Comment by borisd** [comment]
Got it, attached PR https://github.com/markerikson/react-redux-links/pull/56
