### ISSUE TITLE
Dead link: http://blog.isquaredsoftware.com/presentations/2016-10-revolution-of-web-dev/

### ISSUE THREAD

**Issue by Kirupakaran** [markerikson/react-redux-links#61]

**Comment by mdapper** [comment]
For me the link seems to be working, open a presentation called "The (R)Evolution of Web Development".

**Comment by markerikson** [comment]
Yeah, works for me at the moment.  @Kirupakaran , what page or errors are you seeing?

**Comment by markerikson** [comment]
If you see an actual error please let me know, but this appears to be working.

**Comment by Kirupakaran** [comment]
I'm getting a 404 error. 
![screenshot from 2017-06-20 10-28-49](https://user-images.githubusercontent.com/4750711/27317349-6219da90-55a3-11e7-8bcc-b9f3d2edd419.png)

**Comment by markerikson** [comment]
That's... very odd, especially since the links from both the front page README and the "Basic Concepts" page appear to be working fine for me.

Does it work on any other computer or browser?

**Comment by Kirupakaran** [comment]
@markerikson  I found the problem. My company proxy server is blocking it. But, I'm not sure why I'm getting a 404 error. Usually there'll be an explicit message. Also, they don't usually block any websites, only media downloads.

**Comment by markerikson** [comment]
Yeah, I've had reports that my blog is blocked by a couple corporate proxies.  Not entirely sure why, and I'm not sure if there's anything I can do about it.
