### ISSUE TITLE
Suggestion: React Sights

### ISSUE THREAD

**Issue by john-d-pelingo** [markerikson/react-redux-links#78]
Just found this very useful tool https://github.com/React-Sight/React-Sight which is an extension for chrome that visualizes the component hierarchy tree of a React application.

I dunno if this has been discussed. I checked the other issues but haven't found anything related to tooling.

Side note: There doesn't seem to be a markdown for tools. They're just mentioned at the root [README.md.](https://github.com/markerikson/react-redux-links/blob/master/README.md).

I can make a PR with the new file where its first content are
- react devtools
- react sight

Or they can be written somewhere at the [README.md.](https://github.com/markerikson/react-redux-links/blob/master/README.md)?

Looks like redux devtools are on the other repository.

**Comment by markerikson** [comment]
Yeah, I've got a bunch of Redux devtools in the other list, and a few React-related ones as well at the bottom of that page (primarily "did my component update?" stuff).

I've tried to keep this list focused on articles and not tools or libraries thus far.  Not entirely sure if I really want a tools section in this list.

**Comment by john-d-pelingo** [comment]
True. I had this feeling that you wanted to keep it that way. I just wanted to make it sure.
This probably belongs to an awesome list for now.

Thank you for your insight.
