### ISSUE TITLE
Malicious link

### ISSUE THREAD

**Issue by KChen8516** [markerikson/react-redux-links#81]
This might've changed later but this link in the React Forms section contains a bunch of malicious redirects:

http://thereactionary.net/list-or-form-why-not-both-making-a-list-with-a-built-in-editor-in-react/

**Comment by markerikson** [comment]
Thanks.  Yeah, the site appears to be dead.  Had another article from that site linked, too.  

I just pushed an update that replaced both links with Web Archive pointers.
